apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: privileged-pipeline
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:your-project-name:pipeline-account