---
apiVersion: v1
kind: Namespace
metadata:
  name: serverless-demo

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: serverless-demo-app
  namespace: serverless-demo
spec:
  template:
    metadata:
      annotations:
        # Autoscaling configuration
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/window: "60s"
    spec:
      containers:
        - image: quay.io/openshift-knative/knative-eventing-sources-event-display:latest
          env:
            - name: RESPONSE_MESSAGE
              value: "Hello from Serverless!"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing

---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: serverless-demo

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: serverless-demo-trigger
  namespace: serverless-demo
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: serverless-demo-app