apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-serverless
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - image: jsrkamal/own:ocp-serverless-demo1
          ports:
            - containerPort: 9095